feat: add support for proper parsing to dracula
deepsourcelabs/dracula pull request #15
Opened 2023-05-12 10:40 UTC by swarnim-deepsource

use tree-sitter to provide proper means of parsing.

2023-05-16 07:09 UTC, tushar-deepsource commented
@swarnim-deepsource is V2 more reliable than V1? Should we switch test coverage completely to v2?

2023-05-26 07:49 UTC, prajwal-deepsource commented on src/langs/mod.rs
> +pub use scala::Scala;
Not exposing js and jsx?

2023-05-26 08:45 UTC, swarnim-deepsource commented on src/langs/mod.rs
> +pub use scala::Scala;
that's v1, look into pydracula.

2023-05-26 08:47 UTC, prajwal-deepsource commented on src/langs/mod.rs
> +pub use scala::Scala;
Ack, got it

2023-05-26 08:47 UTC, prajwal-deepsource submitted a review, later dismissed

2023-05-26 09:16 UTC, tushar-deepsource commented on src/tests.rs
> +                /* this is part of the string? */ // :04 as this is template string
why `:04`? should be `:05` right

2023-05-26 09:17 UTC, tushar-deepsource reviewed
I'd appreciate it if you can have tests asserting the cleaned source as well, not just line count. Will be more robust.

2023-05-26 10:27 UTC, swarnim-deepsource commented on src/tests.rs
> +                /* this is part of the string? */ // :04 as this is template string
typo :P

2023-05-26 10:27 UTC, swarnim-deepsource commented on src/tests.rs
> +                /* this is part of the string? */ // :04 as this is template string
```suggestion
                /* this is part of the string? */ // :05 as this is template string
```

2023-05-26 10:42 UTC, swarnim-deepsource commented
@tushar-deepsource we don't generate clean_src any more. We don't need to worry about cleaned source because the parsing is out of our hands now, and can be assumed to correct unless it fails cleanly.
I'd appreciate it if you can have tests asserting the cleaned source as well, not just line count. Will be more robust.

2023-05-27 12:40 UTC, tushar-deepsource commented
> and can be assumed to correct unless it fails cleanly.
No I disagree, even if the code is correct the test is not good enough. By just checking the number of valid lines == 7 can pass even if the code is wrong. So at least asserting the exact valid indices would be needed, not just their count.

2023-05-29 11:23 UTC, swarnim-deepsource commented
> No I disagree, even if the code is correct the test is not good enough. By just checking the number of valid lines == 7 can pass even if the code is wrong. So at least asserting the exact valid indices would be needed, not just their count.

@tushar-deepsource we already do index matching, in the run_on_self function.

2023-05-29 11:34 UTC, tushar-deepsource requested changes

2023-05-29 11:34 UTC, tushar-deepsource commented on src/tests.rs
> +        // let lines = count::get_meaningful_line_indices::<Python>(src)
turn these into assertions

2023-05-29 11:34 UTC, tushar-deepsource commented on src/tests.rs
> +        assert_eq!(cnt_executable, 5);
assert indices as well, with the total count

2023-05-30 12:58 UTC, tushar-deepsource approved these changes

2023-05-31 10:04 UTC, merged